FROM luguenin/starcraft2-base:latest AS builder
FROM python:3.12-slim-bullseye

RUN useradd -U -m botuser && chown -R botuser /home/botuser

WORKDIR /home/botuser
COPY --from=builder /home/botuser .

# Remove STDOUT buffering for easier debugging
ENV PYTHONUNBUFFERED=1
USER botuser
